---
# tasks file for roles/win_ad_install
- name: Install AD
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Create new domain
  win_domain:
    dns_domain_name: ad1.2c1a.example.opentlc.com
    safe_mode_password: cmVkaGF0MTIzNDU2OTAK

- name: Reboot the machine with all defaults
  win_reboot:
    reboot_timeout: 3600

- name: List available domain
  win_command: "nltest /dclist:{{ ad_domain_name }}"
  register: list_domain

- name: Debug
  debug:
    var: list_domain


