---
# tasks file for roles/win_ad_user
#- name: Debug
#  debug:
#    msg: "usuario: {{ item.name }}"
#  loop: "{{ user_info.user }}"

- name: Create groups
  win_domain_group:
    name: "{{ item.group.0.group_name }}"
    state: present
    scope: "{{ item.group.0.group_scope }}"
  loop: "{{ user_info.user }}"

- name: Create users
  win_domain_user:
    name: "{{ item.name }}"
    email: "{{ item.email }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    state: present
    #groups:
    #  - "{{ item.group.0.group_name }}"
  loop: "{{ user_info.user }}"

