---
# tasks file for roles/win_ad_user
- name: Create users
  win_domain_user:
    name: "{{ item.0.name }}"
    email: "{{ item.0.email }}"
    firstname: "{{ item.0.firstname }}"
    surname: "{{ item.0.surname }}"
    password: "{{ item.0.password }}"
    state: present
    groups:
      - "{{ item.o.group.group_name }}"
  loop: "{{ user_info.user }}" 

